baseURL = "https://arraiz.github.io/"
title = "arraiz.me"
theme = "hugo-theme-m10c"
defaultContentLanguage = "en"

# Language Configuration
[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    title = "arraiz.me"
    weight = 1
    [languages.en.params]
      author = "Mikel Diez (arraiz)"
      description = "Hackity Hacks"

  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    title = "arraiz.me"
    weight = 2
    [languages.es.params]
      author = "Mikel Diez (arraiz)"
      description = "Hackity Hacks"

  [languages.eu]
    contentDir = "content/eu"
    languageName = "Euskara"
    title = "arraiz.me"
    weight = 3
    [languages.eu.params]
      author = "Mikel Diez (arraiz)"
      description = "Hackity Hacks"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[params]
  author = "Mikel Diez (arraiz)"
  description = "Hackity Hacks"
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/Arraiz"
  [[params.social]]
    icon = "brand-x"
    name = "X"
    url = "https://x.com/arraiz0xF"
#  [[params.social]]
#    icon = "brand-mastodon"
#    name = "Twitter"
#    url = "https://twitter.com/gohugoio"

  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"
